### ISSUE TITLE
Revert feature

### ISSUE THREAD

**Issue by tmartinfr** [peopledoc/django-north#14]
Would it be possible to add a feature to revert applied migrations (similar to the second argument of `migrations.RunSQL` in Django's migration system) ?
It would imply (optionally) to store somewhere reverse SQL statements for each SQL migrations.

For example, my migration contains :

`ALTER TABLE foo ADD COLUMN a int;`

The reverse SQL would be :

`ALTER TABLE foo DROP COLUMN a;`

And a North command would allow to play this reverse SQL if needed.

Typical use cases :
- `a` column has been added using North, but I figure out the type should be `float`. The feature would allow to easily remove the column, modify the migration, and play it again.
- Working on different code branch, I want to cleanly unapply migrations from the current branch before switching to a different one.
- Before pushing a PR with a (potentially complex) North migration, I want to unapply my migration, then play it again, to be sure there is no error.

I've seen the mention in the documentation about the fact that North is only able to go forward, but this feature looks useful for dev. Is it anyway something which can be discuted / submitted in a PR ?

**Comment by ewjoachim** [comment]
Well, the aim of North as we use it is really to have our DBA team write migrations for us, and they really have no interest writing reverse migration. What we're doing is mainly to make sure that our fixtures system is good enough so that we can trash our dev DB 10 times a day. This way we really just write migrations one way.

The good part of that approach is that you write a good fixtures system once, versus you write reverse migrations all the time...

For your 3 usecases, our way of dealing with it is :
- We don't write SQL because DBAs do a better job at it that we do.
- We trash our DB all the time, and replay all migrations.

Would this approach suit your needs too ?

Note : You can maybe look at [populous](https://github.com/novafloss/populous) for quickly generating data, if you need. Or simply [factory boy](https://github.com/pytest-dev/pytest-factoryboy).

**Comment by tmartinfr** [comment]
We sometimes have the need to write our own SQL and iterate fast. In this case, recreating all data everytime seems a bit overkill. This is why losing this possibility looked as a kind of regression for my team when I had to introduce North to them (beside many improvments it brings). I had to discuss that with them. 

The solution is probably to not use North for the write-test-debug-fix cycle when writing SQL, unlike we did with Django's migrations, and only use it for validating the final version before pushing the sql-ddl PR.

I let this issue open if other people want to react, but feel free to close it when you want.

**Comment by ewjoachim** [comment]
Even if you do write your own migrations, you can still use North, as long as you have a way to quickly populate a fresh DB. Revert a migration on a db with placeholder data is really the same as regenerating the data from scratch without this migration.

**Comment by tmartinfr** [comment]
Sure, if it's **really** fast (a few seconds). Currently we don't have the tooling to do that, but if populous is ready, we should considerer to use it at the same time we start to use North (currently we rely on SQL dumps to refresh our database, too slow for our use case).

**Comment by ewjoachim** [comment]
It probably depends a lot on the method used to load that SQL. I've seen DBs with GB of data populated in seconds using `COPY TO` / `COPY FROM` with binary format, and/or db templates.

For example, using DB templates :
https://www.postgresql.org/docs/9.3/static/manage-ag-templatedbs.html
Create a new db named `[your_project]_template`. Run all migration and populate data. Then, edit your settings so that the DB used when doing `manage.py migrate` for merged migrations will be `[your_project]_template`, and then when switching branches, `drobdb [your_project] && createdb [your_project] -t [your_project]_template`.

I'm betting at least 1 🍺 that the last operation doesn't take more that 2 secs.

**Comment by k4nar** [comment]
@tmartinfr : In development I would advise to use simply `psql` to run your files. If you want to revert a migration, simply run the appropriate command in a `psql` shell or create a new file and run it.

If you were suggesting that North should "guess" how a migration should be reversed, well I think this is gonna be very, very complicated :) .

**Comment by tmartinfr** [comment]
@k4nar Of course North cannot guess how to revert. These reverse SQL commands have to be stored somewhere. With Django's migrations they are in the same file than the forward migrations.
Using north, well the forward migrations will be in the sql-ddl repo, and the reverse migrations... somewhere else... and we can play them with psql like you say.
